// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: heating.proto

package heating;

public final class Heating {
  private Heating() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_heating_StringResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_heating_StringResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_heating_IntResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_heating_IntResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_heating_IntRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_heating_IntRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_heating_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_heating_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rheating.proto\022\007heating\"\036\n\016StringRespon" +
      "se\022\014\n\004text\030\001 \001(\t\"\034\n\013IntResponse\022\r\n\005value" +
      "\030\001 \001(\005\"\033\n\nIntRequest\022\r\n\005value\030\001 \001(\005\"\007\n\005E" +
      "mpty2\217\001\n\016HeatingService\022>\n\016setHeatingTem" +
      "p\022\023.heating.IntRequest\032\027.heating.StringR" +
      "esponse\022=\n\025getCurrentHeatingTemp\022\016.heati" +
      "ng.Empty\032\024.heating.IntResponseB\002P\001b\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_heating_StringResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_heating_StringResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_heating_StringResponse_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_heating_IntResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_heating_IntResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_heating_IntResponse_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_heating_IntRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_heating_IntRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_heating_IntRequest_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_heating_Empty_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_heating_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_heating_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
