// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: heating.proto

package heating;

public interface IntResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:heating.IntResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 value = 1;</code>
   */
  int getValue();
}
