// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: speakers.proto

package speakers;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:speakers.Empty)
    com.google.protobuf.MessageOrBuilder {
}
