// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: speakers.proto

package speakers;

public interface IntRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:speakers.IntRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 value = 1;</code>
   */
  int getValue();
}
