// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: speakers.proto

package speakers;

public interface SpeakersSettingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:speakers.SpeakersSetting)
    com.google.protobuf.MessageOrBuilder {
}
