// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: speakers.proto

package speakers;

public final class Speakers {
  private Speakers() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_speakers_IntResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_speakers_IntResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_speakers_IntRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_speakers_IntRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_speakers_StringResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_speakers_StringResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_speakers_SpeakersSetting_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_speakers_SpeakersSetting_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_speakers_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_speakers_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016speakers.proto\022\010speakers\"\034\n\013IntRespons" +
      "e\022\r\n\005value\030\001 \001(\005\"\033\n\nIntRequest\022\r\n\005value\030" +
      "\001 \001(\005\"\036\n\016StringResponse\022\014\n\004text\030\001 \001(\t\"?\n" +
      "\017SpeakersSetting\",\n\007Setting\022\n\n\006CINEMA\020\000\022" +
      "\n\n\006SPORTS\020\001\022\t\n\005MUSIC\020\002\"\007\n\005Empty2\332\002\n\017Spea" +
      "kersService\022:\n\020getCurrentVolume\022\017.speake" +
      "rs.Empty\032\025.speakers.IntResponse\022@\n\014chnag" +
      "eVolume\022\024.speakers.IntRequest\032\030.speakers" +
      ".StringResponse(\001\022N\n\025changeSpeakersSetti" +
      "ng\022\031.speakers.SpeakersSetting\032\030.speakers" +
      ".StringResponse(\001\022;\n\016turnOnSpeakers\022\017.sp" +
      "eakers.Empty\032\030.speakers.StringResponse\022<" +
      "\n\017turnOffSpeakers\022\017.speakers.Empty\032\030.spe" +
      "akers.StringResponseB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_speakers_IntResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_speakers_IntResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_speakers_IntResponse_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_speakers_IntRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_speakers_IntRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_speakers_IntRequest_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_speakers_StringResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_speakers_StringResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_speakers_StringResponse_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_speakers_SpeakersSetting_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_speakers_SpeakersSetting_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_speakers_SpeakersSetting_descriptor,
        new java.lang.String[] { });
    internal_static_speakers_Empty_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_speakers_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_speakers_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
