// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smarttv.proto

package smarttv;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smarttv.Empty)
    com.google.protobuf.MessageOrBuilder {
}
