// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smarttv.proto

package smarttv;

public final class Smarttv {
  private Smarttv() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smarttv_TvSetting_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smarttv_TvSetting_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smarttv_IntResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smarttv_IntResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smarttv_IntRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smarttv_IntRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smarttv_StringResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smarttv_StringResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smarttv_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smarttv_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rsmarttv.proto\022\007smarttv\"9\n\tTvSetting\",\n" +
      "\007Setting\022\n\n\006NORMAL\020\000\022\t\n\005SPORT\020\001\022\n\n\006CINEM" +
      "A\020\002\"\034\n\013IntResponse\022\r\n\005value\030\001 \001(\005\"\033\n\nInt" +
      "Request\022\r\n\005value\030\001 \001(\005\"\036\n\016StringResponse" +
      "\022\014\n\004text\030\001 \001(\t\"\007\n\005Empty2\376\001\n\016SmartTvServi" +
      "ce\0223\n\010turnOnTV\022\016.smarttv.Empty\032\027.smarttv" +
      ".StringResponse\0224\n\tturnOffTV\022\016.smarttv.E" +
      "mpty\032\027.smarttv.StringResponse\022>\n\017changeT" +
      "VSetting\022\022.smarttv.TvSetting\032\027.smarttv.S" +
      "tringResponse\022A\n\021changeVolumeLevel\022\023.sma" +
      "rttv.IntRequest\032\027.smarttv.StringResponse" +
      "B\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_smarttv_TvSetting_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_smarttv_TvSetting_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smarttv_TvSetting_descriptor,
        new java.lang.String[] { });
    internal_static_smarttv_IntResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_smarttv_IntResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smarttv_IntResponse_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_smarttv_IntRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_smarttv_IntRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smarttv_IntRequest_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_smarttv_StringResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_smarttv_StringResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smarttv_StringResponse_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_smarttv_Empty_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_smarttv_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smarttv_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
