// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smarttv.proto

package smarttv;

public final class Smarttv {
  private Smarttv() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smarttv_StringResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smarttv_StringResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smarttv_StringRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smarttv_StringRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smarttv_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smarttv_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rsmarttv.proto\022\007smarttv\"\036\n\016StringRespon" +
      "se\022\014\n\004text\030\001 \001(\t\"\035\n\rStringRequest\022\014\n\004tex" +
      "t\030\001 \001(\t\"\007\n\005Empty2\203\002\n\016SmartTvService\0223\n\010t" +
      "urnOnTv\022\016.smarttv.Empty\032\027.smarttv.String" +
      "Response\0224\n\tturnOffTv\022\016.smarttv.Empty\032\027." +
      "smarttv.StringResponse\022B\n\rconnectToWifi\022" +
      "\026.smarttv.StringRequest\032\027.smarttv.String" +
      "Response0\001\022B\n\rchangeChannel\022\026.smarttv.St" +
      "ringRequest\032\027.smarttv.StringResponse0\001B\002" +
      "P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_smarttv_StringResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_smarttv_StringResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smarttv_StringResponse_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_smarttv_StringRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_smarttv_StringRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smarttv_StringRequest_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_smarttv_Empty_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_smarttv_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smarttv_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
