// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smarttv.proto

package smarttv;

public interface StringRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smarttv.StringRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string text = 1;</code>
   */
  java.lang.String getText();
  /**
   * <code>string text = 1;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
