// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smarttv.proto

package smarttv;

public interface TvSettingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smarttv.TvSetting)
    com.google.protobuf.MessageOrBuilder {
}
