// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lighting.proto

package lighting;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lighting.Empty)
    com.google.protobuf.MessageOrBuilder {
}
