// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lighting.proto

package lighting;

public interface IntRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lighting.IntRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 value = 1;</code>
   */
  int getValue();
}
