// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lighting.proto

package lighting;

/**
 * Protobuf type {@code lighting.LightsSetting}
 */
public  final class LightsSetting extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:lighting.LightsSetting)
    LightsSettingOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LightsSetting.newBuilder() to construct.
  private LightsSetting(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LightsSetting() {
    setting_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private LightsSetting(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            setting_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return lighting.Lighting.internal_static_lighting_LightsSetting_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return lighting.Lighting.internal_static_lighting_LightsSetting_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            lighting.LightsSetting.class, lighting.LightsSetting.Builder.class);
  }

  /**
   * Protobuf enum {@code lighting.LightsSetting.Setting}
   */
  public enum Setting
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>BLUE = 0;</code>
     */
    BLUE(0),
    /**
     * <code>GREEN = 1;</code>
     */
    GREEN(1),
    /**
     * <code>RED = 2;</code>
     */
    RED(2),
    /**
     * <code>ORIGINAL = 3;</code>
     */
    ORIGINAL(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>BLUE = 0;</code>
     */
    public static final int BLUE_VALUE = 0;
    /**
     * <code>GREEN = 1;</code>
     */
    public static final int GREEN_VALUE = 1;
    /**
     * <code>RED = 2;</code>
     */
    public static final int RED_VALUE = 2;
    /**
     * <code>ORIGINAL = 3;</code>
     */
    public static final int ORIGINAL_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Setting valueOf(int value) {
      return forNumber(value);
    }

    public static Setting forNumber(int value) {
      switch (value) {
        case 0: return BLUE;
        case 1: return GREEN;
        case 2: return RED;
        case 3: return ORIGINAL;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Setting>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Setting> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Setting>() {
            public Setting findValueByNumber(int number) {
              return Setting.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return lighting.LightsSetting.getDescriptor().getEnumTypes().get(0);
    }

    private static final Setting[] VALUES = values();

    public static Setting valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Setting(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:lighting.LightsSetting.Setting)
  }

  public static final int SETTING_FIELD_NUMBER = 1;
  private int setting_;
  /**
   * <code>.lighting.LightsSetting.Setting setting = 1;</code>
   */
  public int getSettingValue() {
    return setting_;
  }
  /**
   * <code>.lighting.LightsSetting.Setting setting = 1;</code>
   */
  public lighting.LightsSetting.Setting getSetting() {
    @SuppressWarnings("deprecation")
    lighting.LightsSetting.Setting result = lighting.LightsSetting.Setting.valueOf(setting_);
    return result == null ? lighting.LightsSetting.Setting.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (setting_ != lighting.LightsSetting.Setting.BLUE.getNumber()) {
      output.writeEnum(1, setting_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (setting_ != lighting.LightsSetting.Setting.BLUE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, setting_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof lighting.LightsSetting)) {
      return super.equals(obj);
    }
    lighting.LightsSetting other = (lighting.LightsSetting) obj;

    boolean result = true;
    result = result && setting_ == other.setting_;
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SETTING_FIELD_NUMBER;
    hash = (53 * hash) + setting_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static lighting.LightsSetting parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static lighting.LightsSetting parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static lighting.LightsSetting parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static lighting.LightsSetting parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static lighting.LightsSetting parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static lighting.LightsSetting parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static lighting.LightsSetting parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static lighting.LightsSetting parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static lighting.LightsSetting parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static lighting.LightsSetting parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static lighting.LightsSetting parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static lighting.LightsSetting parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(lighting.LightsSetting prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code lighting.LightsSetting}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:lighting.LightsSetting)
      lighting.LightsSettingOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return lighting.Lighting.internal_static_lighting_LightsSetting_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return lighting.Lighting.internal_static_lighting_LightsSetting_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              lighting.LightsSetting.class, lighting.LightsSetting.Builder.class);
    }

    // Construct using lighting.LightsSetting.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      setting_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return lighting.Lighting.internal_static_lighting_LightsSetting_descriptor;
    }

    @java.lang.Override
    public lighting.LightsSetting getDefaultInstanceForType() {
      return lighting.LightsSetting.getDefaultInstance();
    }

    @java.lang.Override
    public lighting.LightsSetting build() {
      lighting.LightsSetting result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public lighting.LightsSetting buildPartial() {
      lighting.LightsSetting result = new lighting.LightsSetting(this);
      result.setting_ = setting_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof lighting.LightsSetting) {
        return mergeFrom((lighting.LightsSetting)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(lighting.LightsSetting other) {
      if (other == lighting.LightsSetting.getDefaultInstance()) return this;
      if (other.setting_ != 0) {
        setSettingValue(other.getSettingValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      lighting.LightsSetting parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (lighting.LightsSetting) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int setting_ = 0;
    /**
     * <code>.lighting.LightsSetting.Setting setting = 1;</code>
     */
    public int getSettingValue() {
      return setting_;
    }
    /**
     * <code>.lighting.LightsSetting.Setting setting = 1;</code>
     */
    public Builder setSettingValue(int value) {
      setting_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.lighting.LightsSetting.Setting setting = 1;</code>
     */
    public lighting.LightsSetting.Setting getSetting() {
      @SuppressWarnings("deprecation")
      lighting.LightsSetting.Setting result = lighting.LightsSetting.Setting.valueOf(setting_);
      return result == null ? lighting.LightsSetting.Setting.UNRECOGNIZED : result;
    }
    /**
     * <code>.lighting.LightsSetting.Setting setting = 1;</code>
     */
    public Builder setSetting(lighting.LightsSetting.Setting value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      setting_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.lighting.LightsSetting.Setting setting = 1;</code>
     */
    public Builder clearSetting() {
      
      setting_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:lighting.LightsSetting)
  }

  // @@protoc_insertion_point(class_scope:lighting.LightsSetting)
  private static final lighting.LightsSetting DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new lighting.LightsSetting();
  }

  public static lighting.LightsSetting getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LightsSetting>
      PARSER = new com.google.protobuf.AbstractParser<LightsSetting>() {
    @java.lang.Override
    public LightsSetting parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new LightsSetting(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<LightsSetting> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LightsSetting> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public lighting.LightsSetting getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

