// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lighting.proto

package lighting;

public interface LightsSettingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lighting.LightsSetting)
    com.google.protobuf.MessageOrBuilder {
}
