// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lighting.proto

package lighting;

public final class Lighting {
  private Lighting() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lighting_LightsSetting_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lighting_LightsSetting_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lighting_IntResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lighting_IntResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lighting_IntRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lighting_IntRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lighting_StringResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lighting_StringResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lighting_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lighting_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016lighting.proto\022\010lighting\"x\n\rLightsSett" +
      "ing\0220\n\007setting\030\001 \001(\0162\037.lighting.LightsSe" +
      "tting.Setting\"5\n\007Setting\022\010\n\004BLUE\020\000\022\t\n\005GR" +
      "EEN\020\001\022\007\n\003RED\020\002\022\014\n\010ORIGINAL\020\003\"\034\n\013IntRespo" +
      "nse\022\r\n\005value\030\001 \001(\005\"\033\n\nIntRequest\022\r\n\005valu" +
      "e\030\001 \001(\005\"\036\n\016StringResponse\022\014\n\004text\030\001 \001(\t\"" +
      "\007\n\005Empty2\233\002\n\017LightingService\0229\n\014turnOnLi" +
      "ghts\022\017.lighting.Empty\032\030.lighting.StringR" +
      "esponse\022:\n\rturnOffLights\022\017.lighting.Empt" +
      "y\032\030.lighting.StringResponse\022H\n\023changeLig" +
      "htsSetting\022\027.lighting.LightsSetting\032\030.li" +
      "ghting.StringResponse\022G\n\023changeLightingL" +
      "evel\022\024.lighting.IntRequest\032\030.lighting.St" +
      "ringResponse(\001B\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_lighting_LightsSetting_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_lighting_LightsSetting_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lighting_LightsSetting_descriptor,
        new java.lang.String[] { "Setting", });
    internal_static_lighting_IntResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_lighting_IntResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lighting_IntResponse_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_lighting_IntRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_lighting_IntRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lighting_IntRequest_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_lighting_StringResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_lighting_StringResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lighting_StringResponse_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_lighting_Empty_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_lighting_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lighting_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
