// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lighting.proto

package lighting;

public interface LightsSettingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lighting.LightsSetting)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.lighting.LightsSetting.Setting setting = 1;</code>
   */
  int getSettingValue();
  /**
   * <code>.lighting.LightsSetting.Setting setting = 1;</code>
   */
  lighting.LightsSetting.Setting getSetting();
}
