// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smarttv.proto

package lighting;

public final class Smarttv {
  private Smarttv() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lighting_TvSetting_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lighting_TvSetting_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lighting_IntResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lighting_IntResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lighting_IntRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lighting_IntRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lighting_StringResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lighting_StringResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lighting_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lighting_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rsmarttv.proto\022\010lighting\"9\n\tTvSetting\"," +
      "\n\007Setting\022\n\n\006NORMAL\020\000\022\t\n\005SPORT\020\001\022\n\n\006CINE" +
      "MA\020\002\"\034\n\013IntResponse\022\r\n\005value\030\001 \001(\005\"\033\n\nIn" +
      "tRequest\022\r\n\005value\030\001 \001(\005\"\036\n\016StringRespons" +
      "e\022\014\n\004text\030\001 \001(\t\"\007\n\005Empty2\206\002\n\016SmartTvServ" +
      "ice\0225\n\010turnOnTV\022\017.lighting.Empty\032\030.light" +
      "ing.StringResponse\0226\n\tturnOffTV\022\017.lighti" +
      "ng.Empty\032\030.lighting.StringResponse\022@\n\017ch" +
      "angeTVSetting\022\023.lighting.TvSetting\032\030.lig" +
      "hting.StringResponse\022C\n\021changeVolumeLeve" +
      "l\022\024.lighting.IntRequest\032\030.lighting.Strin" +
      "gResponseB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_lighting_TvSetting_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_lighting_TvSetting_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lighting_TvSetting_descriptor,
        new java.lang.String[] { });
    internal_static_lighting_IntResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_lighting_IntResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lighting_IntResponse_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_lighting_IntRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_lighting_IntRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lighting_IntRequest_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_lighting_StringResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_lighting_StringResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lighting_StringResponse_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_lighting_Empty_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_lighting_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lighting_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
