// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smarttv.proto

package lighting;

public interface TvSettingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lighting.TvSetting)
    com.google.protobuf.MessageOrBuilder {
}
